name: Gitlab Runner Service - Ubuntu
on:
  workflow_dispatch:
    inputs:
      tailscale_oauth_client_id:
        description: 'Oauth Client ID'
        required: true
      tailscale_oauth_client_secret:
        description: 'Oauth Client Secret'
        required: true
      tailscale_tags:
        description: 'ACL Tags'
        required: true
      registration_token:
        description: 'GitLab Runner Registration Token'
        required: true
      gitlab_url:
        description: 'GitLab URL'
        required: true
      docker_image:
        description: 'Docker Image'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          oauth-client-id: "${{ inputs.tailscale_oauth_client_id }}"
          oauth-secret: "${{ inputs.tailscale_oauth_client_secret }}"
          tags: "${{ inputs.tailscale_tags }}"
      
      - name: Static DNS Entry
        shell: bash
        run: |
          ping -c 4 10.10.77.19
          echo '10.10.77.19 gitlab.azureolympos.com' | sudo tee -a /etc/hosts
          echo '10.10.77.19 registry.gitlab.azureolympos.com' | sudo tee -a /etc/hosts
          echo '10.10.77.43 vault.azureolympos.com' | sudo tee -a /etc/hosts
          nslookup gitlab.azureolympos.com
          
      - name: GitLab Custom CICD
        uses: metril/gitlab-runner-action@main
        with:
          registration-token: "${{ inputs.registration_token }}"
          gitlab-url: "${{ inputs.gitlab_url }}"
          docker-image: "${{ inputs.docker_image }}"
          name: ${{ github.run_id }}
          tag-list: "githubrunner-ubuntu"
