name: Gitlab Runner Service - Windows
on:
  workflow_dispatch:
    inputs:
      tailscale_authkey:
        description: 'Tailscale Auth Key'
        required: true
      registration_token:
        description: 'GitLab Runner Registration Token'
        required: true
      gitlab_url:
        description: 'GitLab URL'
        required: true
      docker_image:
        description: 'Docker Image'
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: "${{ inputs.tailscale_authkey }}"

      - name: GitLab Custom CICD
        uses: metril/gitlab-runner-action@main
        with:
          registration-token: "${{ inputs.registration_token }}"
          gitlab-url: "${{ inputs.gitlab_url }}"
          docker-image: "${{ inputs.docker_image }}"
          name: ${{ github.run_id }}
          tag-list: "githubrunner-windows"
