name: Gitlab Runner Service - Windows
on:
  workflow_dispatch:
    inputs:
      tailscale_oauth_client_id:
        description: 'Oauth Client ID'
        required: true
      tailscale_oauth_client_secret:
        description: 'Oauth Client Secret'
        required: true
      tailscale_tags:
        description: 'ACL Tags'
        required: true
      registration_token:
        description: 'GitLab Runner Registration Token'
        required: true
      gitlab_url:
        description: 'GitLab URL'
        required: true
      docker_image:
        description: 'Docker Image'
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Masking Variables
        uses: metril/action-hide-sensitive-inputs@main
        
      - name: Chocolatey Install
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        
      - name: Install Tailscale
        shell: powershell
        run: choco install tailscale
        
      - name: Run Tailscale
        shell: powershell
        env:
          AUTHKEY: "${{ inputs.tailscale_oauth_client_secret }}"
          TAGS: "${{ inputs.tailscale_tags }}"
        run: |
          & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey="${env:AUTHKEY}?ephemeral=true&preauthorized=true" --advertise-tags=${env:TAGS} --hostname=$HOSTNAME --accept-routes --accept-dns=true --unattended
        
      - name: Download GitLab Runner
        shell: powershell
        run: Invoke-WebRequest -Uri https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-windows-amd64.exe -OutFile gitlab-runner.exe
        
      - name: Register GitLab Runner
        shell: powershell
        run: .\gitlab-runner.exe register --non-interactive --executor "shell" --url "${{ inputs.gitlab_url }}" --registration-token "${{ inputs.registration_token }}" --tag-list "githubrunner-windows" --run-untagged --locked="false" --name $env:COMPUTERNAME

      - name: Install GitLab Runner Service
        shell: powershell
        run: .\gitlab-runner.exe install
        
      - name: Start GitLab Runner
        shell: powershell
        run: .\gitlab-runner.exe start

      - name: Check Job Status
        shell: powershell
        run: |
          while ($true) {
            $status = Get-WinEvent -ProviderName gitlab-runner
            if (($status | Where-Object -Property Message -Match "Job succeeded") -Or ($status | Where-Object -Property Message -Match "Failed to process runner")) {
              break
            }
            Write-Host "Waiting for job status to change..."
            Start-Sleep -s 10
          }

      - name: Stop GitLab Runner
        shell: powershell
        run: .\gitlab-runner.exe stop

      - name: Unregister GitLab Runner
        shell: powershell
        run: .\gitlab-runner.exe unregister --name $env:COMPUTERNAME


      
