name: Gitlab Runner Service - Windows
on:
  workflow_dispatch:
    inputs:
      tailscale_authkey:
        description: 'Tailscale Auth Key'
        required: true
      registration_token:
        description: 'GitLab Runner Registration Token'
        required: true
      gitlab_url:
        description: 'GitLab URL'
        required: true
      docker_image:
        description: 'Docker Image'
        required: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Chocolatey Install
        shell: powershell
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        
      - name: Install Tailscale
        shell: powershell
        run: choco install tailscale
        
      - name: Run Tailscale
        shell: powershell
        env:
          AUTHKEY: "${{ inputs.tailscale_authkey }}"
        run: |
          & 'C:\Program Files\Tailscale\tailscale.exe' up --authkey "::add-mask::${env:AUTHKEY}" --hostname=$HOSTNAME --accept-routes --unattended

      - name: GitLab Custom CICD
        uses: metril/gitlab-runner-action@main
        with:
          registration-token: "${{ inputs.registration_token }}"
          gitlab-url: "${{ inputs.gitlab_url }}"
          docker-image: "${{ inputs.docker_image }}"
          name: ${{ github.run_id }}
          tag-list: "githubrunner-windows"
